# Generated by Django 4.1.1 on 2022-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Token', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'user_register',
            },
        ),
    ]
