# Generated by Django 4.1.2 on 2022-11-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IsVerified',
            field=models.BooleanField(default=False),
        ),
    ]
