# Generated by Django 4.1.1 on 2022-10-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_service', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('username', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='inscription',
            field=models.BooleanField(default=False),
        ),
    ]
