# Generated by Django 4.1.1 on 2022-11-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_serviceaccount_service_inscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceaccount',
            old_name='username',
            new_name='email',
        ),
    ]
