# Generated by Django 4.1.1 on 2022-11-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_rename_username_serviceaccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='extra',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
