# Generated by Django 4.1.1 on 2022-11-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_serviceaccount_extra_serviceaccount_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='oauth2',
            field=models.BooleanField(default=False),
        ),
    ]
