# Generated by Django 4.1.1 on 2022-10-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='no name', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Action_Mandatory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_action', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Action_Running',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_action', models.IntegerField()),
                ('id_applet', models.IntegerField()),
                ('query_string', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Applet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('activate', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='no name', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction_Mandatory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_reaction', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction_Running',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_reaction', models.IntegerField()),
                ('id_applet', models.IntegerField()),
                ('query_string', models.CharField(default='', max_length=250)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
